### ISSUE TITLE
West Virginia county road network=* retagged

### ISSUE THREAD

**Issue by claysmalley** [osmandapp/OsmAnd-tools#479]
After discussion with the OpenStreetMap US community, we decided to retag the `route=road` relations for West Virginia county roads with a uniform `network=US:WV:County`. This is because "county roads" in West Virginia are actually a state-maintained, state-signed system of secondary roads.

[See here](https://wiki.openstreetmap.org/wiki/United_States_roads_tagging/Routes#West_Virginia) for updated tagging guidelines and shield images. This page may be very slow to load.

Note that this is the word "County" verbatim, **not** replaced with the name of individual counties, such as `network=US:WV:Monongalia`.

**Comment by 1ec5** [comment]
This relates to the long list of counties hard-coded here:

https://github.com/osmandapp/OsmAnd-tools/blob/b2d54f5332f8f296ec777c109de091cdfceb5f71/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java#L658-L684

By the way, West Virginia’s county roads are conventionally marked on signs and maps with a white circle, identical to the symbol OsmAnd uses for state routes in every state. West Virginia’s state routes should actually be marked with a white square. The United States has a decentralized, very diverse system of route shields. It isn’t uncommon for maps to simplify this system to [generic shields](https://wiki.openstreetmap.org/wiki/United_States/Road_signs/Generic_shields) like OsmAnd does, but that approach leads to driver confusion at important junctions. The U.S. mapping community is currently collaborating on a [new Web renderer](https://github.com/ZeLonewolf/openstreetmap-americana/) that strives to represent this system of shields more accurately. OsmAnd is welcome to adopt this work to the extent possible.

**Comment by xmd5a2** [comment]
Fixed according to wiki

**Comment by 1ec5** [comment]
This issue is not fixed. The wiki and OSM have been updated to reflect the new, unified `network` value, but OsmAnd is still listing all the old `network` values without listing the new one. Please reopen this issue. Thanks!

**Comment by xmd5a2** [comment]
To see difference you need to wait for new maps and update OsmAnd

**Comment by 1ec5** [comment]
Ah, I’m seeing osmandapp/OsmAnd-tools@025073b0fa499767b4d022ccf6929b1a34cdb37f now. It wasn’t referenced here because osmandapp/OsmAnd-Issues#1334 doesn’t exist. Sorry for the confusion.

**Comment by 1ec5** [comment]
The following values may need to be restored, because they’re county names in other states. [This proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/County,_city_and_local_highway_networks_in_the_United_States) may eliminate some of them, but I’m not sure which ones yet:

* `clay` (also appears in `US:MN:Clay`, `US:AR:Clay`)
* `boone` (`US:IA:Boone`)
* `grant` (`US:MN:Grant`, `US:WI:Grant`, `US:OK:Grant`)
* `harrison` (`US:IA:Harrison`)
* `jackson` (`US:MN:Jackson`, `US:TX:Jackson`, `US:OK:Jackson`, `US:WI:Jackson`)
* `jefferson` (`US:NY:Jefferson`, `US:WI:Jefferson`, `US:OK:Jefferson`)
* `lewis` (`US:NY:Lewis`)
* `lincoln` (`US:OK:Lincoln`, `US:WI:Lincoln`, `US:MN:Lincoln`)
* `marshall` (`US:OK:Marshall`, `US:IA:Marshall`)
* `mercer` (`US:NJ:Mercer`)
* `wayne` (`US:IA:Wayne`)

**Comment by claysmalley** [comment]
The proposal linked above will not eliminate any of the networks listed. Those network values will all need to be restored.
